# .github/ISSUE_TEMPLATE/task.yml

name: "Task (実行タスク)"
description: "(DoR不要) 1〜2時間で完了する具体的な実行タスクを起票します"
title: "[Task] "
labels: ["Type:Task"]

body:
  - type: markdown
    attributes:
      value: |
        これは `DoR` (開始条件) が不要な `Activity`（行動）です。
        作成されると、自動的に `Ready` に追加されます。

  - type: textarea
    id: context
    attributes:
      label: "概要 (Context)"
      description: "なぜこの Task が必要なのかの「Why」を簡潔に書いてください。"
      placeholder: "XX機能実装のため、YYのAPIを叩く必要がある..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **<重要>**
        作成後、GitHub の Sub-Issue 機能を使って、
        この Task がどの `UserStory` に紐づくのか、親子関係を必ず設定してください。
        単発のタスクなら不要ですが、その場合は Google Tasks での管理を検討してください。

  - type: textarea
    id: dod
    attributes:
      label: "完了条件 (DoD)"
      description: "完了したとみなすための技術的なチェックリストを具体的に書いてください。"
      value: |
        - [ ] 実装が完了している
        - [ ] ユニットテストが書かれ、すべてパスしている
        - [ ] CI がグリーンである
        - [ ] 関連する UserStory の Acceptance Criteria を満たすことが確認できている
    validations:
      required: true
