name: reading log 読書メモ
description: 読書時のメモ書き、概要、自己解釈など。
assignees: []
labels: ["Book"]
projects: [ndxbn/7]
title: （本のタイトル）
body:
  - type: input
    attributes:
      label: 国会図書館サーチでの URL
      description: |
        [国会図書館サーチ](https://ndlsearch.ndl.go.jp) での書籍のページURL
    validations:
      required: true
  - type: input
    attributes:
      label: ISBN
      description: |
        この書籍の ISBN 番号
    validations:
      required: true
