name: 読書メモ
description: 読書時のメモ書き、概要、自己解釈など。
assignees: []
labels: [book]
projects: [ndxbn/7]
title: （本のタイトル）
body:
  - type: input
    attributes:
      label: 読書メモの URL
      description: |
        [Today I Learned リポジトリ](https://github.com/ndxbn/til/new/main/books)にこの本の読書メモのディレクトリを作成し、その URL を入れてください。

        以下、コピペ用
        `README.md`
        
        ```
        ## （本のタイトル）
        国会図書館サーチ： （`https://ndlsearch.ndl.go.jp`）
        
        ISBN：

        ## 目次
        ```
    validations:
      required: true
