name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
    - name: Run cspell
      run: npx cspell "**/*"
    - name: Run cspell for dotfiles
      run: npx cspell ".*/**/*"
