# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: asset/metrics.classic.svg
          user: ndxbn
          template: classic
          #base: header, activity, community, repositories, metadata
          config_output: png
          config_timezone: Asia/Tokyo
          plugin_achievements: true
          plugin_achievements_display: compact
          plugin_achievements_secrets: true
          plugin_achievements_threshold: C
